trigger: none
stages:
    
    - stage: Test_Release_ACR
      jobs:
        - template: template_test.yml
          parameters:
            containerNames: ['repo1']
            containerRegistry: 'harshini docker registry'
    - stage: Build
      displayName: Build image
      jobs:
            - job: Build
              displayName: Build
              steps:
                  - task: PublishBuildArtifacts@1
                    displayName: 'Publish Artifact: artifact1'
                    inputs:
                        PathtoPublish: README.md
                        ArtifactName: artifact1
                  - task: DownloadBuildArtifacts@1
                    inputs:
                      buildType: 'current'
                      downloadType: 'specific'
                      downloadPath: 'C:\Users\Administrator\har-agent\_work\1\harshini'
                  - task: Docker@2
                    inputs:
                      containerRegistry: 'harshini docker registry'
                      repository: 'repo1'
                      command: 'buildAndPush'
                      Dockerfile: '**/Dockerfile'
    - stage: PostBuildCleanup
      displayName: Post Build Cleanup
      jobs:
            - job: Cleanup
              steps:
                - task: CmdLine@2
                  inputs:
                    script: |
                      echo Write your commands here
                      echo Hello world
    - stage: TagBuildWithTested
      displayName: Tag tested Build
      jobs:
            - job: TagBuildWithTested
              displayName: Tag tested Build
              steps:
                  - task: CmdLine@2
                    continueOnError: true
                    inputs:
                     script: |
                      echo Write your commands here
                      echo Hello world
                  - task: PowerShell@2
                    inputs:
                        targetType: inline
                        script: |
                            Write-Host "##vso[build.addbuildtag]tested"
                            
    - stage: TagBuildWithProd
      displayName: Tag Prod build
      jobs:
            - job: TagBuildWithProd
              displayName: Tag Prod build
              steps:
                  - task: CmdLine@2
                    inputs:
                     script: |
                      echo Write your commands here
                      echo Hello world
                  - task: PowerShell@2
                    inputs:
                        targetType: inline
                        script: |
                            Write-Host "##vso[build.addbuildtag]prod"
